{
 "title": "Trunk Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} Rx"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} Tx"
    }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/trunk\", instance=\"localhost:9100\"}",
     "legendFormat": "Trunk Storage"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"localhost:9100\"}",
     "legendFormat": "Host Machine"
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo|veth.|eth.|podman.|tailscale.\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}} Rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo|eth.|veth.|podman.|tailscale.\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}} Tx"
    }
   ]
  },
  {
   "title": "CPU %Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait\"}[$__rate_interval])) * 100) / (count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}