FROM quay.io/trunk-os/control-plane

RUN /bin/echo -e "deb http://deb.debian.org/debian bookworm-backports main contrib\ndeb-src http://deb.debian.org/debian bookworm-backports main contrib" >/etc/apt/sources.list.d/contrib.list

RUN mkdir /package
RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install zfsutils-linux -y
COPY config.yaml /config.yaml

CMD ["buckled", "/config.yaml"]
