FROM docker.io/grafana/grafana:latest

ARG DISABLE_LOGIN=true

ENV GF_AUTH_DISABLE_LOGIN_FORM "${DISABLE_LOGIN}"
ENV GF_AUTH_ANONYMOUS_ENABLED "${DISABLE_LOGIN}"
ENV GF_AUTH_ANONYMOUS_ORG_ROLE "Admin"

COPY provisioning /etc/grafana/provisioning
COPY grafana.ini /etc/grafana/grafana.ini
COPY dashboards /etc/grafana/dashboards
