FROM debian:latest as git

RUN apt-get update -qq && apt-get install git-core -y
RUN git clone https://github.com/trunk-os/panel /panel
WORKDIR /panel
RUN rm -rf .git

FROM docker.io/oven/bun:1-alpine AS builder

COPY --from=git /panel /app

WORKDIR /app
RUN bun install --frozen-lockfile
RUN bun run build

FROM docker.io/caddy:2-alpine
COPY --from=builder /app/dist /srv
COPY Caddyfile /etc/caddy/Caddyfile

# Caddy runs automatically with the default entrypoint
