FROM rust as rust

RUN apt-get update -qq && apt-get install protobuf-compiler libsystemd-dev -y

# yes, I am aware this sucks
RUN git clone https://github.com/trunk-os/control-plane /control-plane
WORKDIR /control-plane
RUN cargo install --path buckle && cargo install --path charon && cargo install --path gild

RUN cp /usr/local/cargo/bin/buckle /usr/bin/buckle && \
    cp /usr/local/cargo/bin/buckled /usr/bin/buckled && \
    cp /usr/local/cargo/bin/charond /usr/bin/charond && \
    cp /usr/local/cargo/bin/charon /usr/bin/charon && \
    cp /usr/local/cargo/bin/gild /usr/bin/gild
